### ISSUE TITLE
Парсинг статей с сериалами

### ISSUE THREAD

**Issue by Dukobpa3** [romanvm/ex.ua.alternative#1]
Типа таких.
http://www.ex.ua/302352
Сейчас показывается описание первого мульта для всех.

**Comment by Dukobpa3** [comment]
Ну и проигрывание таких подборок как плейлист.

**Comment by romanvm** [comment]
Существующий парсер рассчитан на типичные ситуации и находит описания по неким общим признакам. Например, слово "Описание" в начале параграфа. В данном случае общего описания нет вообще, т. е. непонятно, на что ориентироваться. А писать универсальный парсер под все выверты фантазии авторов ex.ua я не буду. Если кто-то хочет, пусть пишет и создает PR.

**Comment by Dukobpa3** [comment]
Тогда может подскажешь как оформлять такие статьи, чтобы они корректно выдавали описание под каждую серию?

**Comment by romanvm** [comment]
В текущей реализации отдельные описания на каждый файл не поддерживаются, только общие описания на все файлы. Это компромисс между информативностью и сложностью кода плагина.

**Comment by Dukobpa3** [comment]
Я сейчас чешу репу как вынести свою медиабиблиотеку куда-то наружу со своих локальных хранилищ. При чем сами файлы мне хранить не особо то и надо. Достаточно чтоб статья содержала ссылку или id из IMDB, TMDB, etc. + ссылку или несколько на сам файл к просмотру.
Примерно то же самое что предоставляет гуглплей, но на халяву :)
Рассматриваю разные варианты. В первую очередь готовые решения. В том числе и профиль в ex.ua. Можно было бы придумать какой-то формат описания статей. И себе в профиль добавлять статьи на каждый айтем библиотеки.
Но касательно ex.ua смущает отсутствие апи. Парсить текст, как по мне, не самая крутая идея.
Может попробовать какую-то блого-платформу. Один айтем - один пост, в метаданные пихать всё что надо, аналогично фейсбучному опенграфу.

**Comment by romanvm** [comment]
Коди поддерживает ссылки на внешний контент внутри простых текстовых файлов с расширением .strm. Такие файлы даже сканируются в медиатеку. Единственная проблема - с такими файлами не работают закладки и отметки просмотренного.

**Comment by Dukobpa3** [comment]
Загуглил. Крутая фича!!
Спасибо.
