### ISSUE TITLE
http://www.ex.ua/uk/video?r=81708

### ISSUE THREAD

**Issue by vinnitu** [romanvm/ex.ua.alternative#4]
Друже! Зробiть будь ласка пошук категорiй в зонi - Відео [UA - українська]

а ще краще якщо була б можливiсть обирати з самої надбудови

Дякую!

**Comment by romanvm** [comment]
Зроблю, якщо буде час і натхнення :smile: Зараз я проектом активно не займаюся, а лише підтримую в робочому стані.

**Comment by vryabokon1705** [comment]
Ну коли вже? :)

**Comment by romanvm** [comment]
It's open source and pull requests are welcomed :smile: Проект написаний давно, і весь цей трешовий код варто переписати заново, бо зараз я на нього без фейспалму дивитися не можу, але нема часу і бажання.

**Comment by vinnitu** [comment]
на щось можна сподiватися? ;-)

**Comment by romanvm** [comment]
Див. гілку `develop`

**Comment by vinnitu** [comment]
There isn’t anything to compare.
master and develop are identical.

**Comment by vinnitu** [comment]
работает! но было бы удобнее менять в самой программе - скажем через ещё один уровень меню типа

[ua]
[ru]
[en]

у будь якому випадку - дякую!

**Comment by romanvm** [comment]
Авторизовані користувачі ex.ua можуть додавати будь-яку сторінку сайту до особистого розділу "Запам'ятовані" та заходити туди з кореневого рівня меню надбудови.
